from typing import Any


DETECTION_CATALOG: tuple[dict[str, Any], ...] = (
    {
        "rule_id": "RULE-004",
        "name": "Unexpected admin login",
        "description": "Flags successful authentication by an administrator account for analyst review.",
        "enabled": True,
        "severity": "HIGH",
        "conditions": [
            {"field": "event_category", "operator": "equals", "value": "authentication"},
            {"field": "username", "operator": "contains", "value": "admin"},
            {"field": "action", "operator": "equals", "value": "login_success"},
        ],
        "tags": ["authentication", "admin", "review"],
    },
    {
        "rule_id": "RULE-005",
        "name": "New user/account",
        "description": "Detects normalized user or account creation events.",
        "enabled": True,
        "severity": "MEDIUM",
        "conditions": [{"field": "event_type", "operator": "equals", "value": "user_created"}],
        "tags": ["account", "persistence"],
    },
    {
        "rule_id": "RULE-006",
        "name": "Firewall blocks from IP",
        "description": "Detects normalized firewall deny events with a source IP.",
        "enabled": True,
        "severity": "MEDIUM",
        "conditions": [
            {"field": "event_category", "operator": "equals", "value": "firewall"},
            {"field": "action", "operator": "equals", "value": "deny"},
            {"field": "source_ip", "operator": "not equals", "value": ""},
        ],
        "tags": ["firewall", "network"],
    },
    {
        "rule_id": "RULE-007",
        "name": "Suspicious process",
        "description": "Detects normalized process creation events for analyst review.",
        "enabled": True,
        "severity": "HIGH",
        "conditions": [{"field": "event_category", "operator": "equals", "value": "process"}],
        "tags": ["process", "execution"],
    },
    {
        "rule_id": "RULE-008",
        "name": "Unexpected service creation",
        "description": "Detects normalized service creation events.",
        "enabled": True,
        "severity": "HIGH",
        "conditions": [{"field": "event_type", "operator": "equals", "value": "service_created"}],
        "tags": ["service", "persistence"],
    },
    {
        "rule_id": "RULE-009",
        "name": "Large outbound burst",
        "description": "Requires volume aggregation over a time window not available to the single-event evaluator.",
        "enabled": True,
        "severity": "HIGH",
        "conditions": [{"field": "event_type", "operator": "equals", "value": "outbound_burst"}],
        "tags": ["network", "correlation-required"],
    },
    {
        "rule_id": "RULE-010",
        "name": "Repeated closed ports",
        "description": "Requires repeated network observations over a time window.",
        "enabled": True,
        "severity": "MEDIUM",
        "conditions": [{"field": "event_type", "operator": "equals", "value": "closed_port"}],
        "tags": ["network", "scanning", "correlation-required"],
    },
    {
        "rule_id": "RULE-011",
        "name": "Successful login after failures",
        "description": "Requires authentication history for the same host and user.",
        "enabled": True,
        "severity": "HIGH",
        "conditions": [{"field": "event_type", "operator": "equals", "value": "login_success_after_failures"}],
        "tags": ["authentication", "correlation-required"],
    },
    {
        "rule_id": "RULE-012",
        "name": "Unusual source for host",
        "description": "Requires a historical host baseline.",
        "enabled": True,
        "severity": "MEDIUM",
        "conditions": [{"field": "event_type", "operator": "equals", "value": "unusual_source"}],
        "tags": ["analytics", "baseline-required"],
    },
    {
        "rule_id": "RULE-013",
        "name": "Brute force pattern",
        "description": "Requires repeated authentication failures over a time window.",
        "enabled": True,
        "severity": "HIGH",
        "conditions": [{"field": "event_type", "operator": "equals", "value": "brute_force_pattern"}],
        "tags": ["authentication", "brute-force", "correlation-required"],
    },
    {
        "rule_id": "RULE-014",
        "name": "Lateral movement indicators",
        "description": "Requires cross-host correlation and is disabled until that context is available.",
        "enabled": True,
        "severity": "CRITICAL",
        "conditions": [{"field": "event_type", "operator": "equals", "value": "lateral_movement"}],
        "tags": ["lateral-movement", "correlation-required"],
    },
    {
        "rule_id": "RULE-015",
        "name": "Suspicious PowerShell",
        "description": "Detects normalized PowerShell process events.",
        "enabled": True,
        "severity": "HIGH",
        "conditions": [{"field": "event_type", "operator": "equals", "value": "powershell"}],
        "tags": ["process", "powershell", "execution"],
    },
)
