"""add_mitre_attack_foundation

Revision ID: 0302ab5f8a2b
Revises: 50f91b96af24
Create Date: 2026-09-27 20:42:37.215904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0302ab5f8a2b'
down_revision: Union[str, Sequence[str], None] = '50f91b96af24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitre_tactic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tactic_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tactic_id', name='uq_mitre_tactic_tactic_id')
    )
    op.create_index(op.f('ix_mitre_tactic_id'), 'mitre_tactic', ['id'], unique=False)
    op.create_index(op.f('ix_mitre_tactic_name'), 'mitre_tactic', ['name'], unique=False)
    op.create_index(op.f('ix_mitre_tactic_tactic_id'), 'mitre_tactic', ['tactic_id'], unique=True)
    op.create_table('mitre_technique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=False),
    sa.Column('parent_technique_id', sa.String(), nullable=True),
    sa.Column('platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('dataset_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_technique_id'], ['mitre_technique.technique_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technique_id', name='uq_mitre_technique_technique_id')
    )
    op.create_index(op.f('ix_mitre_technique_id'), 'mitre_technique', ['id'], unique=False)
    op.create_index(op.f('ix_mitre_technique_name'), 'mitre_technique', ['name'], unique=False)
    op.create_index(op.f('ix_mitre_technique_parent_technique_id'), 'mitre_technique', ['parent_technique_id'], unique=False)
    op.create_index(op.f('ix_mitre_technique_technique_id'), 'mitre_technique', ['technique_id'], unique=True)
    op.create_table('mitre_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('mapping_source', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('evidence_reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_technique.technique_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technique_id', 'target_type', 'target_id', name='uq_mitre_mapping')
    )
    op.create_index(op.f('ix_mitre_mapping_id'), 'mitre_mapping', ['id'], unique=False)
    op.create_index(op.f('ix_mitre_mapping_target_id'), 'mitre_mapping', ['target_id'], unique=False)
    op.create_index(op.f('ix_mitre_mapping_target_type'), 'mitre_mapping', ['target_type'], unique=False)
    op.create_index(op.f('ix_mitre_mapping_technique_id'), 'mitre_mapping', ['technique_id'], unique=False)
    op.create_table('mitre_technique_tactic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(), nullable=False),
    sa.Column('tactic_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tactic_id'], ['mitre_tactic.tactic_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technique_id'], ['mitre_technique.technique_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technique_id', 'tactic_id', name='uq_technique_tactic')
    )
    op.create_index(op.f('ix_mitre_technique_tactic_id'), 'mitre_technique_tactic', ['id'], unique=False)
    op.create_index(op.f('ix_mitre_technique_tactic_tactic_id'), 'mitre_technique_tactic', ['tactic_id'], unique=False)
    op.create_index(op.f('ix_mitre_technique_tactic_technique_id'), 'mitre_technique_tactic', ['technique_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mitre_technique_tactic_technique_id'), table_name='mitre_technique_tactic')
    op.drop_index(op.f('ix_mitre_technique_tactic_tactic_id'), table_name='mitre_technique_tactic')
    op.drop_index(op.f('ix_mitre_technique_tactic_id'), table_name='mitre_technique_tactic')
    op.drop_table('mitre_technique_tactic')
    op.drop_index(op.f('ix_mitre_mapping_technique_id'), table_name='mitre_mapping')
    op.drop_index(op.f('ix_mitre_mapping_target_type'), table_name='mitre_mapping')
    op.drop_index(op.f('ix_mitre_mapping_target_id'), table_name='mitre_mapping')
    op.drop_index(op.f('ix_mitre_mapping_id'), table_name='mitre_mapping')
    op.drop_table('mitre_mapping')
    op.drop_index(op.f('ix_mitre_technique_technique_id'), table_name='mitre_technique')
    op.drop_index(op.f('ix_mitre_technique_parent_technique_id'), table_name='mitre_technique')
    op.drop_index(op.f('ix_mitre_technique_name'), table_name='mitre_technique')
    op.drop_index(op.f('ix_mitre_technique_id'), table_name='mitre_technique')
    op.drop_table('mitre_technique')
    op.drop_index(op.f('ix_mitre_tactic_tactic_id'), table_name='mitre_tactic')
    op.drop_index(op.f('ix_mitre_tactic_name'), table_name='mitre_tactic')
    op.drop_index(op.f('ix_mitre_tactic_id'), table_name='mitre_tactic')
    op.drop_table('mitre_tactic')
    # ### end Alembic commands ###
