"""Add retention models

Revision ID: 1aebca0ed231
Revises: b6d52427f82a
Create Date: 2026-09-30 10:43:41.684781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1aebca0ed231'
down_revision: Union[str, Sequence[str], None] = 'b6d52427f82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanupauditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('initiated_by', sa.String(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('is_dry_run', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('records_examined', sa.Integer(), nullable=True),
    sa.Column('records_deleted', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleanupauditlog_execution_id'), 'cleanupauditlog', ['execution_id'], unique=False)
    op.create_index(op.f('ix_cleanupauditlog_id'), 'cleanupauditlog', ['id'], unique=False)
    op.create_table('retentionpolicy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_logs_days', sa.Integer(), nullable=True),
    sa.Column('normalized_events_days', sa.Integer(), nullable=True),
    sa.Column('detection_results_days', sa.Integer(), nullable=True),
    sa.Column('alerts_days', sa.Integer(), nullable=True),
    sa.Column('behavioral_data_days', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retentionpolicy_id'), 'retentionpolicy', ['id'], unique=False)
    op.drop_index(op.f('ix_alert_agent_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_host_id'), table_name='alert')
    op.drop_index(op.f('ix_event_agent_id'), table_name='event')
    op.drop_index(op.f('ix_event_host_id_timestamp'), table_name='event')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_host_id_timestamp'), 'event', ['host_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_event_agent_id'), 'event', ['agent_id'], unique=False)
    op.create_index(op.f('ix_alert_host_id'), 'alert', ['host_id'], unique=False)
    op.create_index(op.f('ix_alert_agent_id'), 'alert', ['agent_id'], unique=False)
    op.drop_index(op.f('ix_retentionpolicy_id'), table_name='retentionpolicy')
    op.drop_table('retentionpolicy')
    op.drop_index(op.f('ix_cleanupauditlog_id'), table_name='cleanupauditlog')
    op.drop_index(op.f('ix_cleanupauditlog_execution_id'), table_name='cleanupauditlog')
    op.drop_table('cleanupauditlog')
    # ### end Alembic commands ###
