"""add_behavioral_analytics_models

Revision ID: 2ddddabc941f
Revises: 70c4a06360da
Create Date: 2026-09-28 14:37:08.615941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ddddabc941f'
down_revision: Union[str, Sequence[str], None] = '70c4a06360da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('time_window', sa.String(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('variance', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_baseline_entity_id'), 'behavior_baseline', ['entity_id'], unique=False)
    op.create_index(op.f('ix_behavior_baseline_entity_type'), 'behavior_baseline', ['entity_type'], unique=False)
    op.create_index(op.f('ix_behavior_baseline_id'), 'behavior_baseline', ['id'], unique=False)
    op.create_index(op.f('ix_behavior_baseline_metric_name'), 'behavior_baseline', ['metric_name'], unique=False)
    op.create_table('behavior_deviation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('deviation_magnitude', sa.Float(), nullable=False),
    sa.Column('observation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['baseline_id'], ['behavior_baseline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_deviation_baseline_id'), 'behavior_deviation', ['baseline_id'], unique=False)
    op.create_index(op.f('ix_behavior_deviation_entity_id'), 'behavior_deviation', ['entity_id'], unique=False)
    op.create_index(op.f('ix_behavior_deviation_entity_type'), 'behavior_deviation', ['entity_type'], unique=False)
    op.create_index(op.f('ix_behavior_deviation_id'), 'behavior_deviation', ['id'], unique=False)
    op.create_index(op.f('ix_behavior_deviation_metric_name'), 'behavior_deviation', ['metric_name'], unique=False)
    op.create_index(op.f('ix_behavior_deviation_observation_timestamp'), 'behavior_deviation', ['observation_timestamp'], unique=False)
    op.create_table('behavior_deviation_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviation_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['deviation_id'], ['behavior_deviation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_deviation_evidence_deviation_id'), 'behavior_deviation_evidence', ['deviation_id'], unique=False)
    op.create_index(op.f('ix_behavior_deviation_evidence_id'), 'behavior_deviation_evidence', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_deviation_evidence_id'), table_name='behavior_deviation_evidence')
    op.drop_index(op.f('ix_behavior_deviation_evidence_deviation_id'), table_name='behavior_deviation_evidence')
    op.drop_table('behavior_deviation_evidence')
    op.drop_index(op.f('ix_behavior_deviation_observation_timestamp'), table_name='behavior_deviation')
    op.drop_index(op.f('ix_behavior_deviation_metric_name'), table_name='behavior_deviation')
    op.drop_index(op.f('ix_behavior_deviation_id'), table_name='behavior_deviation')
    op.drop_index(op.f('ix_behavior_deviation_entity_type'), table_name='behavior_deviation')
    op.drop_index(op.f('ix_behavior_deviation_entity_id'), table_name='behavior_deviation')
    op.drop_index(op.f('ix_behavior_deviation_baseline_id'), table_name='behavior_deviation')
    op.drop_table('behavior_deviation')
    op.drop_index(op.f('ix_behavior_baseline_metric_name'), table_name='behavior_baseline')
    op.drop_index(op.f('ix_behavior_baseline_id'), table_name='behavior_baseline')
    op.drop_index(op.f('ix_behavior_baseline_entity_type'), table_name='behavior_baseline')
    op.drop_index(op.f('ix_behavior_baseline_entity_id'), table_name='behavior_baseline')
    op.drop_table('behavior_baseline')
    # ### end Alembic commands ###
