"""Add Alert model

Revision ID: 4a02f1d5bab3
Revises: cd2e7205e780
Create Date: 2026-09-26 21:52:18.670354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a02f1d5bab3'
down_revision: Union[str, Sequence[str], None] = 'cd2e7205e780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('description', sa.String(), nullable=True))
    op.add_column('alert', sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False))
    op.add_column('alert', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False))
    op.add_column('alert', sa.Column('host_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_alert_hostname'), table_name='alert')
    op.create_foreign_key(None, 'alert', 'host', ['host_id'], ['id'])
    op.drop_column('alert', 'first_seen_at')
    op.drop_column('alert', 'last_seen_at')
    op.drop_column('alert', 'source_type')
    op.drop_column('alert', 'created_at')
    op.drop_column('alert', 'evidence_links')
    op.drop_column('alert', 'updated_at')
    op.drop_column('alert', 'operating_system')
    op.drop_column('alert', 'message')
    op.drop_column('alert', 'hostname')
    op.add_column('detection_result', sa.Column('alert_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detection_result', 'alert', ['alert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'detection_result', type_='foreignkey')
    op.drop_column('detection_result', 'alert_id')
    op.add_column('alert', sa.Column('hostname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('alert', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('alert', sa.Column('operating_system', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('alert', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('alert', sa.Column('evidence_links', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('alert', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('alert', sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('alert', sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('alert', sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'alert', type_='foreignkey')
    op.create_index(op.f('ix_alert_hostname'), 'alert', ['hostname'], unique=False)
    op.drop_column('alert', 'host_id')
    op.drop_column('alert', 'last_seen')
    op.drop_column('alert', 'first_seen')
    op.drop_column('alert', 'description')
    # ### end Alembic commands ###
