"""Add investigation models

Revision ID: 71af8d4e5bae
Revises: 4a02f1d5bab3
Create Date: 2026-09-27 12:50:23.403663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71af8d4e5bae'
down_revision: Union[str, Sequence[str], None] = '4a02f1d5bab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_id'), 'investigation', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_severity'), 'investigation', ['severity'], unique=False)
    op.create_index(op.f('ix_investigation_status'), 'investigation', ['status'], unique=False)
    op.create_index(op.f('ix_investigation_title'), 'investigation', ['title'], unique=False)
    op.create_table('investigation_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'evidence_type', 'reference_id', name='uq_investigation_evidence')
    )
    op.create_index(op.f('ix_investigation_evidence_evidence_type'), 'investigation_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_investigation_evidence_id'), 'investigation_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_investigation_evidence_reference_id'), 'investigation_evidence', ['reference_id'], unique=False)
    op.create_table('investigation_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_note_id'), 'investigation_note', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_note_id'), table_name='investigation_note')
    op.drop_table('investigation_note')
    op.drop_index(op.f('ix_investigation_evidence_reference_id'), table_name='investigation_evidence')
    op.drop_index(op.f('ix_investigation_evidence_id'), table_name='investigation_evidence')
    op.drop_index(op.f('ix_investigation_evidence_evidence_type'), table_name='investigation_evidence')
    op.drop_table('investigation_evidence')
    op.drop_index(op.f('ix_investigation_title'), table_name='investigation')
    op.drop_index(op.f('ix_investigation_status'), table_name='investigation')
    op.drop_index(op.f('ix_investigation_severity'), table_name='investigation')
    op.drop_index(op.f('ix_investigation_id'), table_name='investigation')
    op.drop_table('investigation')
    # ### end Alembic commands ###
