"""Initial Phase 2 schema

Revision ID: 8c157709b8c7
Revises: 
Create Date: 2026-09-26 15:38:00.822063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c157709b8c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_identifier', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('operating_system', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_host_identifier'), 'host', ['host_identifier'], unique=True)
    op.create_index(op.f('ix_host_hostname'), 'host', ['hostname'], unique=False)
    op.create_index(op.f('ix_host_id'), 'host', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('operating_system', sa.String(), nullable=True),
    sa.Column('agent_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_agent_id'), 'agent', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agent_id'), 'agent', ['id'], unique=False)
    op.create_table('heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('agent_version', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeat_id'), 'heartbeat', ['id'], unique=False)
    op.create_index(op.f('ix_heartbeat_timestamp'), 'heartbeat', ['timestamp'], unique=False)
    op.create_table('raw_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_identifier', sa.String(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingestion_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_log_event_identifier'), 'raw_log', ['event_identifier'], unique=True)
    op.create_index(op.f('ix_raw_log_id'), 'raw_log', ['id'], unique=False)
    op.create_index(op.f('ix_raw_log_source_type'), 'raw_log', ['source_type'], unique=False)
    op.create_index(op.f('ix_raw_log_timestamp'), 'raw_log', ['timestamp'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('operating_system', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('event_category', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('destination_ip', sa.String(), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('raw_log_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.ForeignKeyConstraint(['raw_log_id'], ['raw_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_action'), 'event', ['action'], unique=False)
    op.create_index(op.f('ix_event_destination_ip'), 'event', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_event_event_category'), 'event', ['event_category'], unique=False)
    op.create_index(op.f('ix_event_event_id'), 'event', ['event_id'], unique=True)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=False)
    op.create_index(op.f('ix_event_protocol'), 'event', ['protocol'], unique=False)
    op.create_index(op.f('ix_event_severity'), 'event', ['severity'], unique=False)
    op.create_index(op.f('ix_event_source_ip'), 'event', ['source_ip'], unique=False)
    op.create_index(op.f('ix_event_source_type'), 'event', ['source_type'], unique=False)
    op.create_index(op.f('ix_event_timestamp'), 'event', ['timestamp'], unique=False)
    op.create_index(op.f('ix_event_username'), 'event', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_username'), table_name='event')
    op.drop_index(op.f('ix_event_timestamp'), table_name='event')
    op.drop_index(op.f('ix_event_source_type'), table_name='event')
    op.drop_index(op.f('ix_event_source_ip'), table_name='event')
    op.drop_index(op.f('ix_event_severity'), table_name='event')
    op.drop_index(op.f('ix_event_protocol'), table_name='event')
    op.drop_index(op.f('ix_event_id'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_event_id'), table_name='event')
    op.drop_index(op.f('ix_event_event_category'), table_name='event')
    op.drop_index(op.f('ix_event_destination_ip'), table_name='event')
    op.drop_index(op.f('ix_event_action'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_raw_log_timestamp'), table_name='raw_log')
    op.drop_index(op.f('ix_raw_log_source_type'), table_name='raw_log')
    op.drop_index(op.f('ix_raw_log_id'), table_name='raw_log')
    op.drop_index(op.f('ix_raw_log_event_identifier'), table_name='raw_log')
    op.drop_table('raw_log')
    op.drop_index(op.f('ix_heartbeat_timestamp'), table_name='heartbeat')
    op.drop_index(op.f('ix_heartbeat_id'), table_name='heartbeat')
    op.drop_table('heartbeat')
    op.drop_index(op.f('ix_agent_id'), table_name='agent')
    op.drop_index(op.f('ix_agent_agent_id'), table_name='agent')
    op.drop_table('agent')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_host_id'), table_name='host')
    op.drop_index(op.f('ix_host_hostname'), table_name='host')
    op.drop_index(op.f('ix_host_host_identifier'), table_name='host')
    op.drop_table('host')
    # ### end Alembic commands ###
