"""add_behavior_correlation

Revision ID: b6d52427f82a
Revises: 2ddddabc941f
Create Date: 2026-09-28 14:49:56.760633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d52427f82a'
down_revision: Union[str, Sequence[str], None] = '2ddddabc941f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_correlation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deviation_id', sa.Integer(), nullable=False),
    sa.Column('related_entity_type', sa.String(), nullable=False),
    sa.Column('related_entity_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('relationship_reason', sa.String(), nullable=False),
    sa.Column('time_difference_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deviation_id'], ['behavior_deviation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_correlation_deviation_id'), 'behavior_correlation', ['deviation_id'], unique=False)
    op.create_index(op.f('ix_behavior_correlation_id'), 'behavior_correlation', ['id'], unique=False)
    op.create_index(op.f('ix_behavior_correlation_related_entity_id'), 'behavior_correlation', ['related_entity_id'], unique=False)
    op.create_index(op.f('ix_behavior_correlation_related_entity_type'), 'behavior_correlation', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_behavior_correlation_relationship_type'), 'behavior_correlation', ['relationship_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_correlation_relationship_type'), table_name='behavior_correlation')
    op.drop_index(op.f('ix_behavior_correlation_related_entity_type'), table_name='behavior_correlation')
    op.drop_index(op.f('ix_behavior_correlation_related_entity_id'), table_name='behavior_correlation')
    op.drop_index(op.f('ix_behavior_correlation_id'), table_name='behavior_correlation')
    op.drop_index(op.f('ix_behavior_correlation_deviation_id'), table_name='behavior_correlation')
    op.drop_table('behavior_correlation')
    # ### end Alembic commands ###
