"""Add Alert model

Revision ID: cd2e7205e780
Revises: 916070cf4cd5
Create Date: 2026-09-26 21:48:47.350644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd2e7205e780'
down_revision: Union[str, Sequence[str], None] = '916070cf4cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('operating_system', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('evidence_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_alert_id'), 'alert', ['alert_id'], unique=True)
    op.create_index(op.f('ix_alert_fingerprint'), 'alert', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_alert_hostname'), 'alert', ['hostname'], unique=False)
    op.create_index(op.f('ix_alert_id'), 'alert', ['id'], unique=False)
    op.create_index(op.f('ix_alert_severity'), 'alert', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_status'), 'alert', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_status'), table_name='alert')
    op.drop_index(op.f('ix_alert_severity'), table_name='alert')
    op.drop_index(op.f('ix_alert_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_hostname'), table_name='alert')
    op.drop_index(op.f('ix_alert_fingerprint'), table_name='alert')
    op.drop_index(op.f('ix_alert_alert_id'), table_name='alert')
    op.drop_table('alert')
    # ### end Alembic commands ###
